quick-all:
	./quick_test.sh monoprocess symrob
	./quick_test.sh monoprocess tchecker
	./quick_test.sh multiprocess symrob
	./quick_test.sh multiprocess tchecker
	./quick_test.sh wave symrob
	./quick_test.sh wave tchecker
	./quick_test.sh csma symrob
	./quick_test.sh csma tchecker
full-all:
	./full_test.sh monoprocess symrob
	./full_test.sh monoprocess tchecker
	./full_test.sh multiprocess symrob
	./full_test.sh multiprocess tchecker
	./full_test.sh wave symrob
	./full_test.sh wave tchecker
	./full_test.sh csma symrob
	./full_test.sh csma tchecker
